"use strict";
(function(){
const KEY="adaptive_learning_v9_3_students";
const BANK=window.ALL_BANK||[];
const CURRICULUM=window.CURRICULUM_CATALOG||[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const T={
 quant:{name:"القدرات - كمي",short:"كمي"},verbal:{name:"القدرات - لفظي",short:"لفظي"},step:{name:"STEP",short:"STEP"},
 m3:{name:"ثالث متوسط - المركزي",short:"ثالث متوسط",subjects:["الرياضيات","الإنجليزي","العلوم","لغتي"],weekly:40},
 g5:{name:"خامس ابتدائي",short:"خامس",subjects:["الرياضيات","الإنجليزي"],weekly:20}
};
let state,session=null,timer=null;
function def(){return {version:9,parentPin:"1234",profiles:[
 {id:"p1",name:"الطالبة 1 - قدرات وSTEP",tracks:["quant","verbal","step"],kind:"aptitude"},
 {id:"p2",name:"الطالبة 2 - ثالث متوسط",tracks:["m3"],kind:"school"},
 {id:"p3",name:"الطالبة 3 - خامس ابتدائي",tracks:["g5"],kind:"school"}
],history:[],currentExam:null,externalQuestions:[],appliedPacks:[],scope:{m3:{},g5:{}},remedialPlans:[],remedialProgress:{}}}
function allBank(){const m=new Map();BANK.forEach(q=>m.set(q.id,q));(state.externalQuestions||[]).forEach(q=>m.set(q.id,q));return [...m.values()]}
function academicOrder(q){const m=q?.meta||{},term=Number(m.term||m.semester||1),unit=Number(m.unitOrder||1),lesson=Number(m.lessonOrder||m.sectionOrder||1);return term*1000000+unit*1000+lesson}
function catalogOrder(x){return Number(x.term||1)*1000000+Number(x.unitOrder||1)*1000+Number(x.lessonOrder||1)}
function sections(track,subject){const m=new Map();CURRICULUM.filter(x=>x.track===track&&x.subject===subject).forEach(x=>{const a=catalogOrder(x);m.set(a,{order:a,term:Number(x.term||1),unitOrder:Number(x.unitOrder||1),unit:x.unitTitle||"",lessonOrder:Number(x.lessonOrder||1),lesson:x.lesson||("القسم "+a),catalog:true})});allBank().filter(q=>q.track===track&&q.subject===subject).forEach(q=>{const a=academicOrder(q),mm=q.meta||{};if(!m.has(a))m.set(a,{order:a,term:Number(mm.term||mm.semester||1),unitOrder:Number(mm.unitOrder||1),unit:mm.unitTitle||"",lessonOrder:Number(mm.lessonOrder||mm.sectionOrder||1),lesson:mm.lesson||q.skill||("القسم "+a),catalog:false})});return [...m.values()].sort((a,b)=>a.order-b.order)}
function scopeOptions(a,cur){let out='<option value="0">لم يبدأ بعد</option>',last='';for(const x of a){const key=x.term+'|'+x.unitOrder+'|'+x.unit;if(key!==last){if(last)out+='</optgroup>';out+=`<optgroup label="الفصل الدراسي ${x.term} • ${esc(x.unit)}">`;last=key}out+=`<option value="${x.order}" ${x.order===cur?'selected':''}>${esc(x.lesson)}</option>`}if(last)out+='</optgroup>';return out}
function catalogCount(t,s=null){return CURRICULUM.filter(x=>x.track===t&&(!s||x.subject===s)).length}
function normalize(){const d=def();state={...d,...state};state.profiles=Array.isArray(state.profiles)&&state.profiles.length===3?state.profiles:d.profiles;state.history=Array.isArray(state.history)?state.history:[];state.externalQuestions=Array.isArray(state.externalQuestions)?state.externalQuestions:[];state.appliedPacks=Array.isArray(state.appliedPacks)?state.appliedPacks:[];state.remedialPlans=Array.isArray(state.remedialPlans)?state.remedialPlans:[];state.remedialProgress=state.remedialProgress||{};state.scope={m3:{...(state.scope?.m3||{})},g5:{...(state.scope?.g5||{})}};for(const t of ["m3","g5"]){for(const s of T[t].subjects){const a=sections(t,s);if(a.length&&!(s in state.scope[t]))state.scope[t][s]=a[0].order}}state.version=10}
function load(){try{state=JSON.parse(localStorage.getItem(KEY)||"null")||def();normalize();save();window.STORE_ERR=null}catch(e){state=def();normalize();window.STORE_ERR=e}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));window.STORE_ERR=null}catch(e){window.STORE_ERR=e}}
function page(h){$("app").innerHTML=h;window.scrollTo(0,0)}
function top(title,back="home()") {return `<div class="top"><div><div class="brand">${esc(title)}</div><div class="sub">V10 • ثلاث طالبات • جهاز واحد • تكيف محلي</div></div><button class="btn light sm" onclick="${back}">رجوع</button></div>`}
function warn(){return window.STORE_ERR?`<div class="card warning"><b>الحفظ المحلي غير متاح في طريقة الفتح الحالية.</b><div>استخدم رابط GitHub Pages عبر https حتى تُحفظ النتائج.</div></div>`:""}
function name(t){return T[t]?.name||t}
function profile(pid){return state.profiles.find(p=>p.id===pid)}
function eligible(track,subject=null){let a=allBank().filter(q=>q.track===track);if(subject)a=a.filter(q=>q.subject===subject);if(T[track]?.subjects){a=a.filter(q=>academicOrder(q)<=Number(state.scope?.[track]?.[q.subject]||0))}return a}
function stats(pid,track,subject=null){const m={};state.history.filter(h=>h.profileId===pid).forEach(h=>(h.answers||[]).forEach(a=>{if(a.track!==track)return;if(subject&&a.subject!==subject)return;const k=a.skill||"غير مصنف";if(!m[k])m[k]={skill:k,n:0,c:0,csec:0,cn:0,target:0};const x=m[k];x.n++;x.target+=a.targetSec||60;if(a.correct){x.c++;x.cn++;x.csec+=a.sec||0}}));return Object.values(m).map(x=>{const acc=(x.c+2)/(x.n+4),tar=x.target/Math.max(1,x.n),avg=x.cn?x.csec/x.cn:tar*1.4,sp=Math.max(0,Math.min(1,tar/Math.max(1,avg)));return {...x,accuracy:Math.round(acc*100),avgSec:Math.round(avg),mastery:Math.round(100*(.85*acc+.15*sp))}})}
function mastery(pid,t,s){return stats(pid,t).find(x=>x.skill===s)?.mastery??50}
function trackMastery(pid,t,subject=null){const a=stats(pid,t,subject);return a.length?Math.round(a.reduce((z,x)=>z+x.mastery,0)/a.length):50}
function used(pid){const m={};state.history.filter(h=>h.profileId===pid).forEach(h=>(h.answers||[]).forEach(a=>m[a.qid]=(m[a.qid]||0)+1));return m}
function rnd(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function weightedSelect(pid,t,n,mode,b){if(!b.length)return[];const skills=[...new Set(b.map(q=>q.skill))],sm={};skills.forEach(s=>sm[s]=mastery(pid,t,s));if(mode==="speed")b=b.filter(q=>(sm[q.skill]??50)>=80);const u=used(pid),r=rnd((Date.now()+n+b.length)&0xffffffff);let a=b.map(q=>{const m=sm[q.skill]??50;let w=m<65?6:m<82?3.2:1.2;if(!u[q.id])w*=2.8;else w/=1+Math.min(4,u[q.id]*.75);const wanted=m<60?2:m<80?3:4;w*=1/(1+Math.abs((q.difficulty||2)-wanted)*.35);return {q,w,k:Math.pow(r(),1/Math.max(.1,w))}}).sort((x,y)=>y.k-x.k),out=[],fam={};for(const x of a){const f=x.q.family||x.q.skill,cap=Math.max(2,Math.ceil(n*.3));if((fam[f]||0)>=cap)continue;out.push(x.q);fam[f]=(fam[f]||0)+1;if(out.length>=n)break}if(out.length<n)for(const x of a){if(!out.includes(x.q)){out.push(x.q);if(out.length>=n)break}}return out}
function selectSchool(pid,t,n,mode,subject=null){const b=eligible(t,subject);if(subject)return weightedSelect(pid,t,n,mode,b);const subs=T[t].subjects,base=Math.floor(n/subs.length),rem=n%subs.length,out=[];subs.forEach((s,i)=>out.push(...weightedSelect(pid,t,base+(i<rem?1:0),mode,b.filter(q=>q.subject===s))));return out.sort(()=>Math.random()-.5)}
function countByTrack(){const c={quant:0,verbal:0,step:0,m3:0,g5:0};allBank().forEach(q=>{if(c[q.track]!==undefined)c[q.track]++});return c}
function recentErrors(limit=8){const a=[];state.history.slice().reverse().forEach(h=>(h.answers||[]).slice().reverse().forEach(x=>{if(!x.correct&&a.length<limit)a.push({...x,pid:h.profileId})}));return `<div class="card"><div class="row between"><div class="title">أحدث الأخطاء</div><button class="btn light sm" onclick="errorNotebook()">دفتر الأخطاء</button></div>${a.length?a.map(x=>`<div class="skillrow"><b>${esc(profile(x.pid)?.name||"")} • ${esc(name(x.track))}${x.subject?" • "+esc(x.subject):""}</b><div>${esc(x.skill)}</div><div class="sub">${esc(x.text)}</div></div>`).join(""):"<p class='sub'>لا توجد أخطاء بعد.</p>"}</div>`}
window.home=function(){clearTimer();const c=countByTrack();page(`${warn()}<div class="top"><div><div class="brand">المعلّم الذكي V10</div><div class="sub">قدرات وSTEP • ثالث متوسط مركزي • خامس رياضيات وإنجليزي • الفصلان 1 و2 محملان</div></div></div><div class="card"><div class="title">الدخول</div><div class="grid g2"><button class="btn blue" onclick="parentLogin()">ولي الأمر</button><button class="btn green" onclick="studentChoose()">الطالبة</button></div></div><div class="card"><div class="title">البنك الفعلي</div><div class="grid g5"><div class="stat"><span>كمي</span><b>${c.quant}</b></div><div class="stat"><span>لفظي</span><b>${c.verbal}</b></div><div class="stat"><span>STEP</span><b>${c.step}</b></div><div class="stat"><span>ثالث متوسط</span><b>${c.m3}</b></div><div class="stat"><span>خامس</span><b>${c.g5}</b></div></div></div>`) };
window.parentLogin=function(){page(`${top("دخول ولي الأمر")}<div class="card narrow"><div class="field"><label>PIN</label><input id="pin" type="password" inputmode="numeric" autocomplete="off"></div><button class="btn blue" onclick="checkPin()">دخول</button><div id="pinMsg" class="redText"></div></div>`) };
window.checkPin=function(){if($("pin").value===state.parentPin)parentHome();else $("pinMsg").textContent="PIN غير صحيح"};
window.parentHome=function(){clearTimer();const c=countByTrack();page(`${top("لوحة ولي الأمر")}<div class="nav"><button class="btn blue sm" onclick="parentHome()">الرئيسية</button><button class="btn orange sm" onclick="scopeCenter('m3')">نطاق ثالث متوسط</button><button class="btn orange sm" onclick="scopeCenter('g5')">نطاق خامس</button><button class="btn light sm" onclick="bankExplorer()">البنك</button><button class="btn violet sm" onclick="updatesCenter()">تحديث بنك</button><button class="btn red sm" onclick="errorNotebook()">دفتر الأخطاء</button><button class="btn green sm" onclick="remedialCenter()">الخطة العلاجية</button><button class="btn light sm" onclick="settings()">الإعدادات</button></div><div class="card"><div class="grid g5"><div class="stat"><span>كمي</span><b>${c.quant}</b></div><div class="stat"><span>لفظي</span><b>${c.verbal}</b></div><div class="stat"><span>STEP</span><b>${c.step}</b></div><div class="stat"><span>ثالث</span><b>${c.m3}</b></div><div class="stat"><span>خامس</span><b>${c.g5}</b></div></div></div><div class="grid g3">${state.profiles.map(profileCard).join("")}</div>${recentErrors()}`)};
function profileCard(p){let body="";if(p.kind==="aptitude")body=`<div class="grid g3">${p.tracks.map(t=>`<div class="stat"><span>${esc(T[t].short)}</span><b>${trackMastery(p.id,t)}%</b></div>`).join("")}</div>`;else{const t=p.tracks[0];body=`<div class="grid ${T[t].subjects.length>2?'g4':'g2'}">${T[t].subjects.map(s=>`<div class="stat"><span>${esc(s)}</span><b>${trackMastery(p.id,t,s)}%</b></div>`).join("")}</div>`}return `<div class="card"><div class="row between"><div class="title">${esc(p.name)}</div><span class="pill">${state.history.filter(h=>h.profileId===p.id).length} جلسة</span></div>${body}<button class="btn light" onclick="analytics('${p.id}')">تحليل المهارات</button></div>`}
window.analytics=function(pid){const p=profile(pid),rows=[];p.tracks.forEach(t=>stats(pid,t).forEach(x=>rows.push({...x,track:t})));rows.sort((a,b)=>a.mastery-b.mastery);page(`${top("تحليل "+p.name,"parentHome()")}<div class="card">${rows.length?rows.map(r=>`<div class="skillrow"><div class="row between"><b>${esc(r.skill)}</b><span>${r.mastery}%</span></div><div class="sub">${esc(name(r.track))} • ${r.n} إجابة • دقة ${r.accuracy}% • متوسط الصحيح ${r.avgSec}ث</div><div class="progress"><span style="width:${r.mastery}%"></span></div></div>`).join(""):"<p>لا توجد بيانات بعد.</p>"}</div>`) };
window.studentChoose=function(){page(`${top("اختيار الطالبة")}<div class="grid g3">${state.profiles.map(p=>`<div class="card"><div class="title">${esc(p.name)}</div><div class="sub">${p.kind==='aptitude'?'قدرات كمي • لفظي • STEP':esc(name(p.tracks[0]))}</div><button class="btn green" onclick="studentHome('${p.id}')">دخول</button></div>`).join("")}</div>`) };
function scopeSummary(t){return T[t].subjects.map(s=>{const a=sections(t,s),cur=Number(state.scope[t][s]||0),x=a.find(z=>z.order===cur);return `<span class="pill">${esc(s)}: ${esc(x?.lesson||'لم يبدأ')}</span>`}).join(' ')}
window.studentHome=function(pid){clearTimer();const p=profile(pid),resume=state.currentExam?.profileId===pid;let h=`${top(p.name,"studentChoose()")}${resume?`<div class="card success"><b>يوجد اختبار غير مكتمل.</b><div class="row"><button class="btn green sm" onclick="resumeExam()">متابعة</button><button class="btn light sm" onclick="discardExam('${pid}')">إلغاء</button></div></div>`:""}${studentRemedialCard(pid)}`;if(p.kind==='aptitude'){h+=`<div class="card hero"><div class="title">اختبار الأسبوع</div><div class="sub">60 سؤالًا: 20 كمي + 20 لفظي + 20 STEP</div><button class="btn blue" onclick="startWeekly('${pid}')">ابدئي اختبار الأسبوع</button></div><div class="grid g3">${p.tracks.map(t=>trackCard(pid,t)).join("")}</div>`}else{const t=p.tracks[0];h+=`<div class="card info"><b>نطاقك الحالي من الدروس</b><div class="row" style="margin-top:8px">${scopeSummary(t)}</div></div><div class="card hero"><div class="title">اختبار الأسبوع</div><div class="sub">${t==='m3'?'40 سؤالًا: 10 لكل مادة':'20 سؤالًا: 10 رياضيات + 10 إنجليزي'}</div><button class="btn blue" onclick="startWeekly('${pid}')">ابدئي اختبار الأسبوع</button></div><div class="grid ${T[t].subjects.length>2?'g2':'g2'}">${T[t].subjects.map(s=>subjectCard(pid,t,s)).join("")}</div>`}page(h)};
function trackCard(pid,t){const b=eligible(t),m=trackMastery(pid,t),w=stats(pid,t).sort((a,b)=>a.mastery-b.mastery).slice(0,3);return `<div class="card"><div class="row between"><div class="title">${esc(name(t))}</div><span class="pill">${m}%</span></div><div class="sub">المتاح: ${b.length} سؤال</div><div class="progress"><span style="width:${m}%"></span></div><div class="small">${w.length?'الأولوية: '+w.map(x=>`${esc(x.skill)} ${x.mastery}%`).join(' • '):'سيبدأ بتحديد المستوى.'}</div><div class="row"><button class="btn blue" ${b.length?'':'disabled'} onclick="setupExam('${pid}','${t}','weekly','')">اختبار</button><button class="btn light" ${b.length?'':'disabled'} onclick="setupExam('${pid}','${t}','practice','')">تدريب</button><button class="btn orange" ${b.length?'':'disabled'} onclick="setupExam('${pid}','${t}','speed','')">سرعة</button></div></div>`}
function subjectCard(pid,t,s){const b=eligible(t,s),m=trackMastery(pid,t,s),cur=sections(t,s).find(x=>x.order===Number(state.scope[t][s]||0));return `<div class="card"><div class="row between"><div class="title">${esc(s)}</div><span class="pill">إتقان ${m}%</span></div><div class="sub">حتى: ${esc(cur?.lesson||'لم يبدأ')} • ${b.length} سؤال</div><div class="progress"><span style="width:${m}%"></span></div><div class="row"><button class="btn blue" ${b.length?'':'disabled'} onclick="setupExam('${pid}','${t}','weekly','${esc(s)}')">اختبار</button><button class="btn light" ${b.length?'':'disabled'} onclick="setupExam('${pid}','${t}','practice','${esc(s)}')">تدريب</button></div></div>`}
window.startWeekly=function(pid){const p=profile(pid);let qs=[];if(p.kind==='aptitude'){qs.push(...weightedSelect(pid,'quant',20,'weekly',eligible('quant')),...weightedSelect(pid,'verbal',20,'weekly',eligible('verbal')),...weightedSelect(pid,'step',20,'weekly',eligible('step')))}else{const t=p.tracks[0],n=T[t].weekly;qs=selectSchool(pid,t,n,'weekly')}if(!qs.length)return alert('لا توجد أسئلة مناسبة ضمن النطاق الحالي');qs.sort(()=>Math.random()-.5);session={id:'WK_'+Date.now(),profileId:pid,track:'weekly',mode:'weekly',questions:qs,index:0,answers:[],startedAt:Date.now(),selected:null};state.currentExam=session;save();renderQ()};
window.setupExam=function(pid,t,mode,subject){const b=T[t]?.subjects?eligible(t,subject||null):eligible(t);const speedOK=mode!=='speed'||[...new Set(b.map(q=>q.skill))].some(s=>mastery(pid,t,s)>=80);page(`${top("إعداد "+(subject?subject:name(t)),`studentHome('${pid}')`)}<div class="card"><div class="field"><label>عدد الأسئلة</label><input id="cnt" type="number" min="5" max="${Math.max(5,b.length)}" value="${Math.min(subject?10:20,Math.max(5,b.length))}"></div><div class="info">يُعطي المحرك أولوية للمهارات الأضعف وللأسئلة غير المستخدمة قدر الإمكان.</div><button class="btn blue" ${!b.length||!speedOK?'disabled':''} onclick="startExam('${pid}','${t}','${mode}','${esc(subject||'')}')">ابدئي</button></div>`) };
window.startExam=function(pid,t,mode,subject){const n=Math.max(5,+$("cnt").value||10),qs=T[t]?.subjects?selectSchool(pid,t,n,mode,subject||null):weightedSelect(pid,t,n,mode,eligible(t));if(!qs.length)return alert('لا توجد أسئلة مناسبة');session={id:'EX_'+Date.now(),profileId:pid,track:t,subject:subject||'',mode,questions:qs,index:0,answers:[],startedAt:Date.now(),selected:null};state.currentExam=session;save();renderQ()};
window.resumeExam=function(){session=state.currentExam;if(session)renderQ()};window.discardExam=function(pid){if(confirm('إلغاء الاختبار غير المكتمل؟')){state.currentExam=null;save();studentHome(pid)}};
function renderQ(){clearTimer();const q=session.questions[session.index],n=session.questions.length;session.qStartedAt=Date.now();state.currentExam=session;save();page(`<div class="card sticky"><div class="row between"><div><b>${session.mode==='remedial'?'تدريب علاجي':session.mode==='weekly'?'اختبار الأسبوع':esc(name(q.track))}</b><div class="sub">سؤال ${session.index+1}/${n}${q.subject?' • '+esc(q.subject):''} • ${esc(q.skill)}</div></div><div id="clock" class="clock">00:00</div></div><div class="progress"><span style="width:${100*session.index/n}%"></span></div></div><div class="card"><div class="row"><span class="pill">صعوبة ${q.difficulty||2}/5</span><span class="pill">هدف ${q.targetSec||60}ث</span>${q.meta?.lesson?`<span class="pill">${esc(q.meta.lesson)}</span>`:''}</div><div class="qtext">${esc(q.text).replace(/\n/g,'<br>')}</div><div class="answers">${q.options.map((o,i)=>`<button id="ans${i}" class="answer" onclick="selectAnswer(${i})"><b>${['أ','ب','ج','د'][i]||i+1}</b> — ${esc(o)}</button>`).join('')}</div><div id="feed"></div><div class="row"><button id="next" class="btn blue" disabled onclick="submitAnswer(false)">التالي</button><button class="btn light" onclick="abortExam()">إنهاء دون حفظ</button></div></div>`);startTimer(q)}
window.selectAnswer=function(i){session.selected=i;document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));$('ans'+i).classList.add('selected');$('next').disabled=false};
window.submitAnswer=function(timeout=false){if(session.selected==null&&!timeout)return;const q=session.questions[session.index],sec=Math.max(1,Math.round((Date.now()-session.qStartedAt)/1000)),sel=timeout?-1:session.selected,correct=sel===q.answer;session.answers.push({qid:q.id,track:q.track,skill:q.skill,subject:q.subject||'',text:q.text,correct,sec,targetSec:q.targetSec||60,selected:sel});if(['practice','remedial'].includes(session.mode)&&!timeout){document.querySelectorAll('.answer').forEach((x,i)=>{x.disabled=true;if(i===q.answer)x.classList.add('correct');if(i===sel&&!correct)x.classList.add('wrong')});$('feed').innerHTML=`<div class="${correct?'success':'warning'}"><b>${correct?'صحيح':'غير صحيح'}</b><div>${esc(q.explanation||'')}</div></div>`;$('next').textContent=session.index===session.questions.length-1?'إنهاء':'السؤال التالي';$('next').onclick=advance}else advance();state.currentExam=session;save()};
function advance(){session.index++;session.selected=null;if(session.index>=session.questions.length)finish();else renderQ()}
function finish(){clearTimer();const c=session.answers.filter(x=>x.correct).length,n=session.answers.length,score=Math.round(100*c/Math.max(1,n)),sec=Math.round((Date.now()-session.startedAt)/1000),pid=session.profileId,weak={};session.answers.filter(x=>!x.correct).forEach(x=>weak[x.skill]=(weak[x.skill]||0)+1);state.history.push({id:session.id,profileId:pid,track:session.track,mode:session.mode,score,totalSec:sec,finishedAt:Date.now(),answers:session.answers});if(session.remedial){const pr=progressFor(session.remedial.packId);pr.attempts[session.remedial.dayNo]=(pr.attempts[session.remedial.dayNo]||0)+1;if(score>=70&&!pr.completedDays.includes(Number(session.remedial.dayNo)))pr.completedDays.push(Number(session.remedial.dayNo))}state.currentExam=null;save();const groups={};session.answers.forEach(a=>{const k=a.subject||T[a.track]?.short||a.track;if(!groups[k])groups[k]={n:0,c:0};groups[k].n++;if(a.correct)groups[k].c++});page(`${top('النتيجة',`studentHome('${pid}')`)}<div class="card"><div class="grid g3"><div class="stat"><span>النتيجة</span><b>${score}%</b></div><div class="stat"><span>صحيح</span><b>${c}/${n}</b></div><div class="stat"><span>الوقت</span><b>${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}</b></div></div></div><div class="card"><div class="title">التفصيل</div><div class="grid g4">${Object.entries(groups).map(([k,v])=>`<div class="stat"><span>${esc(k)}</span><b>${v.c}/${v.n}</b></div>`).join('')}</div></div>${session.remedial?`<div class="card ${score>=70?'success':'warning'}"><b>${score>=70?'تم اجتياز تدريب اليوم':'يحتاج تدريب اليوم إلى إعادة'}</b><div>الهدف 70% على الأقل.</div></div>`:''}<div class="card"><div class="title">الأولوية القادمة</div>${Object.keys(weak).length?Object.entries(weak).map(([s,x])=>`<div class="skillrow"><b>${esc(s)}</b><div class="sub">${x} خطأ: سترتفع أولوية هذه المهارة.</div></div>`).join(''):"<div class='success'>لا أخطاء؛ سيرفع المحرك الصعوبة تدريجيًا.</div>"}</div>`) }
window.abortExam=function(){if(confirm('إنهاء دون حفظ؟')){const p=session.profileId;state.currentExam=null;save();studentHome(p)}};
function startTimer(q){clearTimer();timer=setInterval(()=>{const c=$('clock');if(!c)return;const s=Math.round((Date.now()-session.qStartedAt)/1000);c.textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;if(session.mode==='speed'&&s>=(q.targetSec||60)){clearTimer();submitAnswer(true)}},500)}function clearTimer(){if(timer){clearInterval(timer);timer=null}}
window.scopeCenter=function(t){const subs=T[t].subjects;page(`${top('نطاق '+name(t),'parentHome()')}<div class="card success"><b>الفصلان الدراسيان الأول والثاني محملان داخل النسخة.</b><div>الاختيار الآن من <b>القسم/الدرس داخل الوحدة</b> وليس من الوحدة كاملة. اختر آخر قسم وصلت إليه الطالبة؛ لن تدخل الأقسام اللاحقة في النطاق.</div><div class="sub">إجمالي فهرس المنهج المحمل لهذا المسار: ${catalogCount(t)} قسمًا/درسًا.</div></div>${subs.map((s,i)=>{const a=sections(t,s),cur=Number(state.scope[t][s]||0),x=a.find(z=>z.order===cur);return `<div class="card"><div class="row between"><div class="title">${esc(s)}</div><span class="pill">${catalogCount(t,s)} قسمًا محملًا</span></div><div class="field"><label>آخر درس/قسم تم الوصول إليه</label><select id="sc_${i}">${scopeOptions(a,cur)}</select></div><div class="sub">${x?`المحدد: الفصل الدراسي ${x.term} • ${esc(x.unit)} • ${esc(x.lesson)}`:'لم يبدأ بعد'}<br>الأسئلة المتاحة حتى هذا النطاق: ${eligible(t,s).length}</div></div>`}).join('')}<button class="btn blue" onclick="saveScope('${t}')">حفظ النطاق</button>`) };
window.saveScope=function(t){T[t].subjects.forEach((s,i)=>state.scope[t][s]=Number($('sc_'+i).value||0));save();alert('تم حفظ نطاق الدروس');scopeCenter(t)};
window.bankExplorer=function(){const b=allBank(),tracks=['quant','verbal','step','m3','g5'];page(`${top('بنك الأسئلة','parentHome()')}<div class="card info"><b>فهرس المنهج منفصل عن عدد الأسئلة.</b><div class="sub">الفصلان الأول والثاني موجودان كاملين في فهرس ثالث متوسط وخامس. عدد الأسئلة أدناه هو المحتوى التدريبي الفعلي الحالي، ويمكن زيادته بحزم لاحقة دون تغيير فهرس المنهج.</div></div>${tracks.map(t=>{const q=b.filter(x=>x.track===t);if(!q.length&&!T[t]?.subjects)return'';if(!T[t]?.subjects){const m={};q.forEach(x=>m[x.skill]=(m[x.skill]||0)+1);return `<div class="card"><div class="row between"><div class="title">${esc(name(t))}</div><span class="pill">${q.length}</span></div>${Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,40).map(([s,n])=>`<div class="skillrow row between"><span>${esc(s)}</span><b>${n}</b></div>`).join('')}</div>`}return `<div class="card"><div class="row between"><div class="title">${esc(name(t))}</div><span class="pill">${q.length} سؤال</span></div>${T[t].subjects.map(s=>`<div class="skillrow"><b>${esc(s)}</b><div class="sub">${q.filter(x=>x.subject===s).length} سؤال • ${catalogCount(t,s)} قسم/درس في فهرس الفصلين</div></div>`).join('')}</div>`}).join('')}`) };
function applyPack(d){if(!d||!Array.isArray(d.questions)||!['adaptive-question-update','adaptive-curriculum-pack','adaptive-term-update','adaptive-central-pack'].includes(d.packType))throw new Error('ملف التحديث غير صالح');const m=new Map(state.externalQuestions.map(q=>[q.id,q]));let added=0,updated=0;d.questions.forEach((q,i)=>{const x={...q,id:q.id||`${d.packId||'PACK'}_${i}`,family:q.family||q.skill};if(['m3','g5'].includes(x.track)){x.meta={...(x.meta||{})};x.meta.term=Number(x.meta.term||x.meta.semester||d.term||d.semester||1);x.meta.unitOrder=Number(x.meta.unitOrder||1);x.meta.lessonOrder=Number(x.meta.lessonOrder||x.meta.sectionOrder||1);}if(!x.track||!x.skill||!x.text||!Array.isArray(x.options)||!Number.isInteger(x.answer))return;if(m.has(x.id))updated++;else added++;m.set(x.id,x)});state.externalQuestions=[...m.values()];const id=d.packId||('pack_'+Date.now()),rec={packId:id,count:d.questions.length,date:d.date||new Date().toISOString().slice(0,10)},j=state.appliedPacks.findIndex(p=>p.packId===id);if(j>=0)state.appliedPacks[j]=rec;else state.appliedPacks.push(rec);normalize();save();return{added,updated}}
window.updatesCenter=function(){page(`${top('تحديث البنك','parentHome()')}<div class="card info"><b>لا تحتاج لإضافة وحدات الفصل الثاني لاحقًا؛ فهرس الفصلين 1 و2 محمل مسبقًا.</b><div class="sub">هذه الصفحة أصبحت لإضافة أو تحسين <b>الأسئلة</b> فقط. حزم ثالث متوسط وخامس يمكنها ربط كل سؤال بالفصل والوحدة والقسم بواسطة meta.term وmeta.unitOrder وmeta.lessonOrder وmeta.lesson، ولن تمسح النتائج السابقة.</div></div><div class="card"><div class="field"><label>ملف JSON</label><input id="updateFile" type="file" accept=".json,application/json"></div><button class="btn violet" onclick="applyUpdateFile()">تطبيق تحديث الأسئلة</button></div><div class="card"><div class="title">التحديثات المثبتة</div>${state.appliedPacks.length?state.appliedPacks.slice().reverse().map(p=>`<div class="skillrow"><b>${esc(p.packId)}</b><div class="sub">${p.count} سؤال • ${esc(p.date||'')}</div></div>`).join(''):"<p class='sub'>لا توجد تحديثات خارجية بعد.</p>"}</div>`) };
window.applyUpdateFile=async function(){const f=$('updateFile').files[0];if(!f)return alert('اختر ملفًا');try{const r=applyPack(JSON.parse(await f.text()));alert(`تم: ${r.added} جديد، ${r.updated} تحديث`);updatesCenter()}catch(e){alert(e.message)}};
function questionMap(){return new Map(allBank().map(q=>[q.id,q]))}
function errorRows(pid='all',track='all',days='7'){const qm=questionMap(),rows=[],cut=days==='all'?0:Date.now()-Number(days)*864e5;state.history.forEach(h=>{if(pid!=='all'&&h.profileId!==pid)return;if((h.finishedAt||0)<cut)return;(h.answers||[]).forEach(a=>{if(a.correct)return;if(track!=='all'&&a.track!==track)return;const q=qm.get(a.qid),selected=a.selected===-1?'انتهى الوقت':(q?.options?.[a.selected]??'غير معروف'),correct=q?.options?.[q.answer]??'غير معروف';rows.push({date:new Date(h.finishedAt||Date.now()).toISOString(),profileId:h.profileId,profileName:profile(h.profileId)?.name||h.profileId,track:a.track,trackName:name(a.track),subject:a.subject||q?.subject||'',skill:a.skill||q?.skill||'',qid:a.qid,text:a.text||q?.text||'',selectedText:selected,correctText:correct,explanation:q?.explanation||'',seconds:a.sec||0,targetSec:a.targetSec||q?.targetSec||60})})});return rows.sort((a,b)=>b.date.localeCompare(a.date))}
function dl(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.errorNotebook=function(){page(`${top('دفتر الأخطاء','parentHome()')}<div class="card"><div class="grid g3"><div class="field"><label>الطالبة</label><select id="errPid"><option value="all">كل الطالبات</option>${state.profiles.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>المسار</label><select id="errTrack"><option value="all">كل المسارات</option>${['quant','verbal','step','m3','g5'].map(t=>`<option value="${t}">${esc(name(t))}</option>`).join('')}</select></div><div class="field"><label>الفترة</label><select id="errDays"><option value="7">آخر 7 أيام</option><option value="14">آخر 14 يومًا</option><option value="30">آخر 30 يومًا</option><option value="all">كل السجل</option></select></div></div><div class="row"><button class="btn blue" onclick="refreshErrors()">عرض</button><button class="btn green" onclick="exportErrors()">تصدير لـ ChatGPT</button></div></div><div id="errView"></div>`);refreshErrors()};
window.refreshErrors=function(){const rows=errorRows($('errPid')?.value||'all',$('errTrack')?.value||'all',$('errDays')?.value||'7');$('errView').innerHTML=`<div class="card"><div class="title">${rows.length} خطأ</div>${rows.length?`<div style="overflow:auto"><table><thead><tr><th>الطالبة</th><th>المسار</th><th>المادة</th><th>المهارة</th><th>السؤال</th><th>إجابتها</th><th>الصحيح</th></tr></thead><tbody>${rows.slice(0,250).map(r=>`<tr><td>${esc(r.profileName)}</td><td>${esc(r.trackName)}</td><td>${esc(r.subject)}</td><td>${esc(r.skill)}</td><td>${esc(r.text)}</td><td class="redText">${esc(r.selectedText)}</td><td>${esc(r.correctText)}</td></tr>`).join('')}</tbody></table></div>`:"<p class='sub'>لا توجد أخطاء ضمن الفلتر.</p>"}</div>`};
window.exportErrors=function(){const pid=$('errPid').value,track=$('errTrack').value,days=$('errDays').value,rows=errorRows(pid,track,days);dl({reportType:'adaptive-v10-error-report',generatedAt:new Date().toISOString(),profile:pid,track,days,errors:rows},`Errors_V10_${new Date().toISOString().slice(0,10)}.json`)};
function progressFor(id){if(!state.remedialProgress[id])state.remedialProgress[id]={completedDays:[],attempts:{}};return state.remedialProgress[id]}
function remedialPlanFor(pid){return state.remedialPlans.filter(p=>!p.profileId||p.profileId===pid).sort((a,b)=>String(b.importedAt||'').localeCompare(String(a.importedAt||'')))[0]||null}
function studentRemedialCard(pid){const p=remedialPlanFor(pid);if(!p)return'';const pr=progressFor(p.packId),days=p.days||[],next=days.find(d=>!pr.completedDays.includes(Number(d.day)));if(!next)return `<div class="card success"><b>الخطة العلاجية مكتملة.</b><div>${esc(p.title||'')}</div></div>`;return `<div class="card violetBox"><div class="row between"><div><div class="title">تدريب اليوم</div><div class="sub">${esc(p.title||'خطة علاجية')} • اليوم ${next.day}</div></div><button class="btn violet" onclick="openRemedial('${p.packId}',${Number(next.day)},'${pid}')">ابدئي</button></div><b>${esc(next.title||'مراجعة')}</b></div>`}
window.remedialCenter=function(){page(`${top('الخطة العلاجية','parentHome()')}<div class="card info"><b>استورد خطة علاجية بصيغة adaptive-remedial-pack.</b></div><div class="card"><div class="field"><label>ملف الخطة</label><input id="remFile" type="file" accept=".json,application/json"></div><button class="btn violet" onclick="importRemedialPack()">استيراد</button></div><div class="card"><div class="title">الخطط المثبتة</div>${state.remedialPlans.length?state.remedialPlans.slice().reverse().map(p=>`<div class="skillrow"><b>${esc(p.title||p.packId)}</b><div class="sub">${esc(profile(p.profileId)?.name||'كل الطالبات')} • ${(progressFor(p.packId).completedDays||[]).length}/${(p.days||[]).length} أيام</div></div>`).join(''):"<p class='sub'>لا توجد خطة بعد.</p>"}</div>`) };
window.importRemedialPack=async function(){const f=$('remFile').files[0];if(!f)return alert('اختر ملفًا');try{const d=JSON.parse(await f.text());if(d.packType!=='adaptive-remedial-pack'||!Array.isArray(d.days))throw new Error('ملف خطة غير صالح');d.packId=d.packId||('rem_'+Date.now());d.importedAt=new Date().toISOString();const i=state.remedialPlans.findIndex(x=>x.packId===d.packId);if(i>=0)state.remedialPlans[i]=d;else state.remedialPlans.push(d);save();alert('تم استيراد الخطة');remedialCenter()}catch(e){alert(e.message)}};
window.openRemedial=function(packId,dayNo,pid){const p=state.remedialPlans.find(x=>x.packId===packId),d=p?.days?.find(x=>Number(x.day)===Number(dayNo));if(!d)return;page(`${top('تدريب اليوم',`studentHome('${pid}')`)}<div class="card"><div class="title">${esc(d.title||'مراجعة')}</div><div class="info">${esc(d.explanation||'').replace(/\n/g,'<br>')}</div>${(d.steps||[]).map((x,i)=>`<div class="skillrow"><b>${i+1}.</b> ${esc(x)}</div>`).join('')}<button class="btn violet" onclick="startRemedialExam('${packId}',${dayNo},'${pid}')">ابدئي الأسئلة</button></div>`) };
window.startRemedialExam=function(packId,dayNo,pid){const p=state.remedialPlans.find(x=>x.packId===packId),d=p?.days?.find(x=>Number(x.day)===Number(dayNo)),qs=(d?.questions||[]).map((q,i)=>({...q,id:q.id||`${packId}_D${dayNo}_Q${i+1}`,track:q.track||'remedial',subject:q.subject||'علاجي',skill:q.skill||d.title||'علاج',difficulty:q.difficulty||1,targetSec:q.targetSec||90,family:q.family||q.skill||d.title||'علاج'}));if(!qs.length)return alert('لا توجد أسئلة في هذا اليوم');session={id:'RX_'+Date.now(),profileId:pid,track:'remedial',mode:'remedial',questions:qs,index:0,answers:[],startedAt:Date.now(),selected:null,remedial:{packId,dayNo}};state.currentExam=session;save();renderQ()};
window.settings=function(){page(`${top('الإعدادات','parentHome()')}<div class="card"><div class="title">أسماء الطالبات</div>${state.profiles.map((p,i)=>`<div class="field"><label>الطالبة ${i+1}</label><input id="nm${i}" value="${esc(p.name)}"></div>`).join('')}<button class="btn blue" onclick="saveNames()">حفظ</button></div><div class="card"><div class="title">PIN ولي الأمر</div><input id="npin" type="password" inputmode="numeric"><button class="btn light" onclick="savePin()">تغيير</button></div><div class="card"><div class="title">نسخة احتياطية</div><button class="btn green" onclick="backup()">تنزيل JSON</button><input id="rest" class="hidden" type="file" accept=".json,application/json" onchange="restoreData(event)"><button class="btn light" onclick="$('rest').click()">استعادة</button></div>`) };
window.saveNames=function(){state.profiles.forEach((p,i)=>p.name=$('nm'+i).value.trim()||p.name);save();alert('تم')};window.savePin=function(){const v=$('npin').value.trim();if(v.length<4)return alert('4 أرقام أو أكثر');state.parentPin=v;save();alert('تم')};
window.backup=function(){dl(state,'adaptive_v10_backup.json')};window.restoreData=async function(e){try{const d=JSON.parse(await e.target.files[0].text());if(!d.profiles||!d.history)throw new Error('ملف غير صالح');state=d;normalize();save();alert('تمت الاستعادة');settings()}catch(x){alert(x.message)}};
window.addEventListener('error',e=>{const f=$('fatal');if(f){f.style.display='block';f.textContent='خطأ تشغيل: '+(e.message||'غير معروف')}});
load();home();if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
